#!/bin/bash
#PBS -q normal
#PBS -P m18
#PBS -l walltime=48:00:00
#PBS -l mem=32GB
#PBS -l ncpus=32
#PBS -l wd


cd ..

module purge
module load gcc/4.7.3
module load python/2.7.5
module load mpi4py
module load openmpi/1.6.3
module load hdf5/1.8.10p
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0
export PYTHONPATH=$PYTHONPATH:$HOME/underworld2

mpirun -np 32 python saved_models/A0.py $PBS_ARRAY_INDEX
